### ISSUE TITLE
Expansion board

### ISSUE THREAD

**Issue by kasbert** [Elrori/EBAZ4205#1]
Please, would you upload the mentioned expansion board files to this repository ?
(https://programmersought.com/article/80046040945/  -> https://download.csdn.net/download/weixin_42157664/13073716 )
I am not able to download them.

**Comment by Elrori** [comment]
Hi,

This download requires payment. I also made a VGA expansion board myself, which will be uploaded to the repo of ebaz4205

日常之夏,

**Comment by kasbert** [comment]
I see. Thanks.

I am planning to make an expansion board with power, HDMI connector, camera header and a some PMOD headers, but I am an newbie with FPGAs and PCBs.
